export const browserCoreExamples = [
  "propel browser status",
  "propel browser start",
  "propel browser stop",
  "propel browser tabs",
  "propel browser open https://example.com",
  "propel browser focus abcd1234",
  "propel browser close abcd1234",
  "propel browser screenshot",
  "propel browser screenshot --full-page",
  "propel browser screenshot --ref 12",
  "propel browser snapshot",
  "propel browser snapshot --format aria --limit 200",
  "propel browser snapshot --efficient",
  "propel browser snapshot --labels",
];

export const browserActionExamples = [
  "propel browser navigate https://example.com",
  "propel browser resize 1280 720",
  "propel browser click 12 --double",
  'propel browser type 23 "hello" --submit',
  "propel browser press Enter",
  "propel browser hover 44",
  "propel browser drag 10 11",
  "propel browser select 9 OptionA OptionB",
  "propel browser upload /tmp/propel/uploads/file.pdf",
  'propel browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "propel browser dialog --accept",
  'propel browser wait --text "Done"',
  "propel browser evaluate --fn '(el) => el.textContent' --ref 7",
  "propel browser console --level error",
  "propel browser pdf",
];
